# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=160)),
                ('publishdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
