# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0004_tweet_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='myTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=160)),
                ('publish_date', models.DateField(auto_now=True)),
                ('html', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
